# Generated by Django 2.0.3 on 2018-04-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('perú', 'PE'), ('colombia', 'CO'), ('mexico', 'MX'), ('estados unidos', 'USA'), ('argentina', 'AR')], max_length=3),
        ),
    ]
