# Generated by Django 2.0.3 on 2018-04-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nacianality',
            new_name='nacionality',
        ),
    ]
